openapi: 3.1.0
info:
  version: 1.0.0
  title: DataAnalysis
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of DataAnalysis app
servers:
  - url: http://127.0.0.1:8000/api
tags:
  - name: Auth
    description: Operation for auth.
  - name: Users
    description: Operation with users.
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml  
  /users/current:
    get:
      $ref: ../swagger/paths/users/current/get.yaml
    patch:
      $ref: ../swagger/paths/users/current/patch.yaml  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
